### ISSUE TITLE
List of RSS feed parsing failure reports

### ISSUE THREAD

**Issue by Ashinch** [Ashinch/ReadYou#13]
Collection of unparsable RSS feed links.

**Comment by Ashinch** [comment]
@S-Sajith

https://feeds.feedburner.com/variety/headlines

https://deadline.com/feed/

https://astronomy.com/rss/news

https://www.wired.com/feed

https://www.wionews.com/feeds/india-news/rss.xml

https://ftr.fivefilters.net/makefulltextfeed.php?url=jalopnik.com/rss&max=3&links=preserve

https://feeds.feedburner.com/carthrottle

https://www.autocarindia.com/rss/all

https://www.youtube.com/feeds/videos.xml?channel_id=UCRcgy6GzDeccI7dkbbBna3Q

**Comment by noClaps** [comment]
https://signal.org/blog/rss.xml
https://surveillancereport.tech/feed

These also don't work

**Comment by Donkey-Doug** [comment]
Reddit does not work. for example:

http://www.reddit.com/r/apple/.rss

**Comment by Donkey-Doug** [comment]
Youtube does not work:

https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw

**Comment by ItamiWasTaken** [comment]
also this 
https://grapheneos.org/releases.atom

**Comment by Nogooduser** [comment]
Can't parse any of these:

https://www.axios.com/feeds/feed.rss

http://www.androidauthority.com/feed/

https://www.rtp.pt/noticias/rss/mundo

http://feeds.jn.pt/JN-ULTIMAS

**Comment by Donkey-Doug** [comment]
On http://www.phonearena.com/feed the articles get fetched correctly, but all time stamps are set to 00:00.

**Comment by S-Sajith** [comment]
These sites don't parse even after switching to Rome

http://www.wionews.com/feeds/india-news/rss.xml
http://www.space.com/feeds/all

**Comment by bauripalash** [comment]
> * [x]  https://signal.org/blog/rss.xml
> 
>     * [x]  https://surveillancereport.tech/feed
> 
> 
> These also don't work

Both of them working on latest release

**Comment by Nogooduser** [comment]
> Can't parse any of these:
> 
> - [x] https://www.axios.com/feeds/feed.rss
> 
> - [ ] http://www.androidauthority.com/feed/
> 
> - [x] https://www.rtp.pt/noticias/rss/mundo
> 
> - [x] http://feeds.jn.pt/JN-ULTIMAS
> 
> 

All of them work in the latest release now.

**Comment by enchainingrealm** [comment]
Can't parse on version 0.8.0:
- [ ] https://www.quillette.com/rss/

**Comment by bakinazik** [comment]
- [ ] https://www.gercekgundem.com/rss
Version: 0.8.1

**Comment by gerard87** [comment]
https://www.androidpolice.com/feed/

Doesn't show images

**Comment by ayaen** [comment]
> also this
> 
> * [x]  https://grapheneos.org/releases.atom

What is the issue with this one?
It is working for me.

**Comment by FredMan95** [comment]
https://cinehdplus.net/peliculas/feed

Items are not organized correctly by date

**Comment by shawn1thompson** [comment]
https://www.abuaminaelias.com/dailyhadithonline/

**Comment by woodvale** [comment]
https://itsfoss.com/feed
Can't fetch images

**Comment by wsu808** [comment]
Tumblr RSSs don't work:  
e.g. https://yamino.tumblr.com/rss  
returns the message(under the input field):  
`Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference`

Version 0.8.3

**Comment by e-zk** [comment]
https://secret.club/feed.xml  

Version 0.8.3

Shows message:

```
Row too big to fit into CursorWindow   
requiredPos=0, totalRows=10
```

**Comment by Liorst4** [comment]
- [ ] https://www.freebsd.org/news/feed.xml
- [ ] https://blog.llvm.org/index.xml

No error message pops up.
I just see their archive feed as empty.

**Comment by vaisakhv** [comment]
While adding YouTube rss feed links it's getting added and updates are being show in the feed but all the channel's counter is set to 15 even after I marked all as read

**Comment by Evilhotdog** [comment]
> * [ ]  https://www.freebsd.org/news/feed.xml
> 
>     * [ ]  https://blog.llvm.org/index.xml
> 
> 
> No error message pops up. I just see their archive feed as empty.

https://www.freebsd.org/security/feed.xml seems to work, on the other hand

Comparing them in W3C's feed validator makes me think it's because it's UTF but reported by the server as ASCII

**Comment by yellowblimp** [comment]
http://www.trueachievements.com/newsrss.aspx

Doesn't load articles. Just the first line. 

https://www.purexbox.com/feeds/news

Doesn't load images.

**Comment by KorneevVitaly** [comment]
https://news.google.com/rss
Doesn't load articles content.

**Comment by JanWaldhorn** [comment]
- [ ] [rss.golem.de](https://rss.golem.de/rss.php?feed=ATOM1.0)

shows only the cookie banner

`
Cookies zustimmen 
Besuchen Sie [Golem.de](http://golem.de/) wie gewohnt mit Werbung und Tracking, indem Sie der Nutzung aller Cookies zustimmen. Details zum Tracking finden Sie im Privacy Center. 
....
`

**Comment by zica87** [comment]
https://forum.endeavouros.com/c/important-notifications/125.rss
Can't subscrible.
Error message: `topCandidate.parent() must not be null`

**Comment by m1su7u** [comment]
Unable to subscribe to any of the feeds mentioned [here](https://indianexpress.com/syndication/).       
For example: https://indianexpress.com/section/world/feed/      
Error message: `Invalid XML: Error on line 19: At line 19, column 35: not well-formed (invalid token)`

**Comment by daeluk** [comment]
RSS feeds of Mastodon accounts in the form of `https://mastodon.instance/@user.rss` don't work, e.g.:

- [ ] https://mastodon.social/@workingclasshistory.rss

Throws `Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference`

Thank you for working on this app!

**Comment by DerpyPlayz18** [comment]
Any Nitter RSS feed link from any instance that supports it, for example:

- [ ] https://nitter.unixfox.eu/NintendoAmerica/rss/

Trows:
`Invalid XML: Error on line 6: At line 6, column 2: mismatched tag`

**Comment by EncryptedCicada** [comment]
- [ ] https://www.phoronix.com/rss.php

It has been a while since it stopped parsing articles so I can't pinpoint the version it broke. Although I'm pretty sure this has something to do with Cloudflare as prior to them using Cloudflare it was working fine.

**Comment by Ashinch** [comment]
> * [ ]  https://www.phoronix.com/rss.php
> 
> It has been a while since it stopped parsing articles so I can't pinpoint the version it broke. Although I'm pretty sure this has something to do with Cloudflare as prior to them using Cloudflare it was working fine.

@EncryptedCicada 

seems to work

<img width="366" alt="image" src="https://github.com/Ashinch/ReadYou/assets/17985933/9d645970-4a31-4639-b0ea-095d3c11e428">

**Comment by EncryptedCicada** [comment]
> > * [ ]  https://www.phoronix.com/rss.php
> > 
> > It has been a while since it stopped parsing articles so I can't pinpoint the version it broke. Although I'm pretty sure this has something to do with Cloudflare as prior to them using Cloudflare it was working fine.
> 
> @EncryptedCicada 
> 
> seems to work
> 
> <img width="366" alt="image" src="https://github.com/Ashinch/ReadYou/assets/17985933/9d645970-4a31-4639-b0ea-095d3c11e428">

The articles aren't loading though. I'm sorry if I put this issue in the wrong thread.

**Comment by Ashinch** [comment]
> 
> The articles aren't loading though. I'm sorry if I put this issue in the wrong thread.

Hi, @EncryptedCicada 

It looks good, if the next `0.9.12` version doesn't solve your problem, please open a separate issue. Sorry, too many responses in this issue will disturb others.

<img width="344" alt="image" src="https://github.com/Ashinch/ReadYou/assets/17985933/66594321-525f-47ef-b080-5d27bcd44f64">

<img width="346" alt="image" src="https://github.com/Ashinch/ReadYou/assets/17985933/09c9978d-bb0a-41ba-af31-6736c4fb794e">

**Comment by Simulping** [comment]
https://huggingface.co/blog/feed.xml
Nothing loads whatsoever.

![Screenshot_2024-02-13-18-01-55-587-edit_me ash reader](https://github.com/Ashinch/ReadYou/assets/12994794/915f7463-bc16-4d4e-ab99-499f1fde07f4)

**Comment by JunkFood02** [comment]
@Simulping Enable "Parse Full Content" for this feed

**Comment by Simulping** [comment]
@JunkFood02 dang it, my mistake. Sorry

**Comment by MartV0** [comment]
- [ ] https://www.i-programmer.info/index.php?option=com_ninjarsssyndicator&feed_id=3&format=raw this one is giving an invalid document error

**Comment by Vysp3r** [comment]
- [ ] https://www.debugpoint.com/feed/
getting error:"stream was reset: PROTOCOL_ERROR"

**Comment by Drsheppard01** [comment]
Time is wrong in atom feeds like [phoronix](https://www.phoronix.com/rss.php) and other feeds with tag <pubDate>

**Comment by 8uff3r** [comment]
> Time is wrong in atom feeds like [phoronix](https://www.phoronix.com/rss.php) and other feeds with tag <pubDate>

I can't add Phoronix at all. The app gives me a "Invalid XML" error.

**Comment by MDfly7** [comment]
#1161

**Comment by candideu** [comment]
Version: 0.15.3
Device: Google Pixel 5a
System: Android 14 (API 34)

Stack trace: 

```java.lang.IllegalArgumentException: feedId is null
	at me.ash.reader.domain.service.GoogleReaderRssService.subscribe(GoogleReaderRssService.kt:535)
	at me.ash.reader.domain.service.GoogleReaderRssService$subscribe$1.invokeSuspend(GoogleReaderRssService.kt:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:7)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:126)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4aeee52, Dispatchers.Default]
```

**Comment by MDfly7** [comment]
#1211 #1202

**Comment by MDfly7** [comment]
Close

**Comment by mdcc7844-art** [comment]
#1236

**Comment by mdcc7844-art** [comment]
#1157

**Comment by mdcc7844-art** [comment]
#1105 #1123 #1004

**Comment by mdcc7844-art** [comment]
#264 #332 #467

**Comment by zse4t7i** [comment]
https://feed.iplaysoft.com/

Feeder can parse it, but ReadYou says invalid XML.
