### ISSUE TITLE
订阅时出现错误

### ISSUE THREAD

**Issue by mrliu714** [Ashinch/ReadYou#646]
**1. Environment**

-   Device: [Xiaomi Redmi K30 5G]
-   OS: [Android 13]
-   APP: [0.9.12]

**2. Describe the bug**
我在订阅https://rsshub.app/agefans/update
这个链接时出现错误
下面是错误报告：
Version: 0.9.12
Device: Xiaomi Redmi K30 5G
System: Android 12 (API 31)

Stack trace: 

java.lang.NullPointerException
	at me.ash.reader.infrastructure.rss.RssHelper.buildArticleFromSyndEntry(RssHelper.kt:177)
	at me.ash.reader.infrastructure.rss.RssHelper.buildArticleFromSyndEntry$default(RssHelper.kt:10)
	at me.ash.reader.domain.service.AbstractRssRepository.subscribe$suspendImpl(AbstractRssRepository.kt:181)
	at me.ash.reader.domain.service.AbstractRssRepository.subscribe(AbstractRssRepository.kt:1)
	at me.ash.reader.ui.page.home.feeds.subscribe.SubscribeViewModel$subscribe$1.invokeSuspend(SubscribeViewModel.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@853d269, Dispatchers.Default]

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)_

**Comment by JunkFood02** [comment]
Fixed in https://github.com/Ashinch/ReadYou/commit/441368695cffd992181f08184139bbdc792cf346
