### ISSUE TITLE
图片资源加载失败

### ISSUE THREAD

**Issue by ron159** [Ashinch/ReadYou#698]
Version: 0.9.12
Device: OPPO PGEM10
System: Android 14 (API 34)

Stack trace: 

java.lang.IllegalArgumentException: MIME type application/json cannot be inserted into content://media/external_primary/images/media; expected MIME type under image/*
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:589)
	at android.content.ContentResolver.insert(ContentResolver.java:2241)
	at android.content.ContentResolver.insert(ContentResolver.java:2197)
	at me.ash.reader.infrastructure.storage.AndroidImageDownloader$downloadImage$2.invokeSuspend(AndroidImageDownloader.kt:161)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1b50d7, Dispatchers.Main.immediate]

**Comment by Ashinch** [comment]
能定位到是哪张图片在哪个场景在出错的吗？

**Comment by ron159** [comment]
> 能定位到是哪张图片在哪个场景在出错的吗？

主要是在煎蛋的无聊图订阅里面出现，因为煎蛋要检查referer，所以用cloudflare的worker做了个反代，实际请求域名走的cloudflare，不清楚是否和这个有关；不过同样网络环境下feeedme很少出现加载不出图片的情况
复现路径：煎蛋无聊图订阅列表里面的缩略图已经显示了，点击进去是裂开的默认图，再点进去后点右上角保存，基本必现（这个问题，我刚还能复现）

如果有时间的话可以试试我这个订阅源：https://rsshub.techkoala.net/jandan/top
