### ISSUE TITLE
OPMLDataSourceTest errors in setUp about mockContext.currentAccountId

### ISSUE THREAD

**Issue by hufman** [Ashinch/ReadYou#770]
**1. Environment**

-   IDE: Android Studio 2023.1.1, with project's gradlew
-   OS: Windows 11
-   APP: 0.10.1  573fead2d

**2. Describe the bug**

The recently added [OPMLDataSourceTest](https://github.com/Ashinch/ReadYou/commit/f9bb04c2e7d04322cd915e7bd57f9bc06a22c1ba#diff-eb6791006ba40b413b9e40a96636ec108db08dcee9b59ecbbae9e03aedb6d7cc) test case does not succeed in my environment. I think my environment is running the underlying extension function as part of mocking `` `when`(mockContext.currentAccountId).thenReturn(1) ``:

```
applicationContext must not be null
java.lang.NullPointerException: applicationContext must not be null
	at androidx.datastore.preferences.PreferenceDataStoreSingletonDelegate.getValue(PreferenceDataStoreDelegate.android.kt:106)
	at androidx.datastore.preferences.PreferenceDataStoreSingletonDelegate.getValue(PreferenceDataStoreDelegate.android.kt:80)
	at me.ash.reader.ui.ext.DataStoreExtKt.getDataStore(DataStoreExt.kt:24)
	at me.ash.reader.ui.ext.DataStoreExtKt.getCurrentAccountId(DataStoreExt.kt:31)
	at me.ash.reader.infrastructure.rss.OPMLDataSourceTest.setUp(OPMLDataSourceTest.kt:51)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

I tried a few alternative ways to set up the mock, but I can't get this test to work. How do you get the unit tests to pass in your environment?

**Comment by hufman** [comment]
I've [prepared a commit](https://github.com/BimmerGestalt/ReadYou/commit/50a150d363672c7b6a32770e6ac8ed96f0cdcfe8) that runs the unit tests in Github Actions, to demonstrate the issue and for a future PR if you'd like.

**Comment by aualbert** [comment]
This does not work on my side either.

**Comment by hufman** [comment]
I [drafted a workaround](https://github.com/Ashinch/ReadYou/compare/main...BimmerGestalt:ReadYou:preferences_manager) that provides an explicit PreferencesReader injectable as a concrete class to mock, instead of trying to mock extension methods, and it works for me.
I'm not sure if this is the best place for this class within the project architecture, or if it should be changed to just receive a Preferences collection or the overall Settings data class or specific Preference keys. Let me know what you think, and I could update the other Context.datastore usages to match.

**Comment by Ashinch** [comment]
Done ✅
