### ISSUE TITLE
Bug Crash

### ISSUE THREAD

**Issue by candideu** [Ashinch/ReadYou#803]
Version: 0.10.1
Device: Google Pixel 5a
System: Android 14 (API 34)

Stack trace: 

java.lang.IllegalArgumentException: feedId is null
	at me.ash.reader.domain.service.GoogleReaderRssService.subscribe(GoogleReaderRssService.kt:507)
	at me.ash.reader.domain.service.GoogleReaderRssService$subscribe$1.invokeSuspend(GoogleReaderRssService.kt:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e11fec8, Dispatchers.Default]

**Comment by Ashinch** [comment]
Hi, @candideu 

What service provider is this Google Reader from? it doesn't look like it supports subscribing to new feeds via the API, so an error occurred.

**Comment by candideu** [comment]
@Ashinch I'm not using Google Reader, but I am syncing with FreshRSS

**Comment by candideu** [comment]
Ran into the issue again:

Version: 0.10.1
Device: Google Pixel 5a
System: Android 14 (API 34)

Stack trace: 

java.lang.IllegalArgumentException: feedId is null
	at me.ash.reader.domain.service.GoogleReaderRssService.subscribe(GoogleReaderRssService.kt:507)
	at me.ash.reader.domain.service.GoogleReaderRssService$subscribe$1.invokeSuspend(GoogleReaderRssService.kt:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d6b0b49, Dispatchers.Default]

**Comment by candideu** [comment]
Ran into the issue again:

Version: 0.11.1
Device: Google Pixel 5a
System: Android 14 (API 34)

Stack trace: 

java.lang.Exception: Unsupported
	at me.ash.reader.domain.service.GoogleReaderRssService.changeFeedUrl(GoogleReaderRssService.kt:5)
	at me.ash.reader.ui.page.home.feeds.drawer.feed.FeedOptionViewModel$changeFeedUrl$1$1.invokeSuspend(FeedOptionViewModel.kt:71)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1c054d0, Dispatchers.Default]
