### ISSUE TITLE
Random crash while reading 

### ISSUE THREAD

**Issue by AndreaDiNapoli** [Ashinch/ReadYou#812]
Version: 0.10.1
Device: Google Pixel 6a
System: Android 14 (API 34)

Stack trace: 

java.net.ConnectException: Failed to connect to /192.168.178.45:49999
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:144)
	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:42)
	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:3)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:16)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@35f0796, Dispatchers.IO]
Caused by: java.net.ConnectException: failed to connect to /192.168.178.45 (port 49999) from /100.118.132.20 (port 60574) after 30000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
	at libcore.io.IoBridge.isConnected(IoBridge.java:347)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:6)
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:79)
	... 7 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
	at libcore.io.IoBridge.isConnected(IoBridge.java:334)
	... 17 more

**Comment by anthonymag** [comment]
This just happened to me and it was because my FreshRSS is on an internal DNS which when I'm away from home only works over my Wireguard VPN.

I kept getting this crash because my DNS wasn't being resolved through my VPN. Toggling the VPN fixed it. The app could handle this more gracefully.
