### ISSUE TITLE
Unable to add a morsst.it feed

### ISSUE THREAD

**Issue by Dav-d** [Ashinch/ReadYou#823]
Version: 0.10.1
Device: HUAWEI ELE-L29
System: Android 10 (API 29)

Stack trace: 

java.lang.IllegalArgumentException: feedId is null
	at me.ash.reader.domain.service.GoogleReaderRssService.subscribe(GoogleReaderRssService.kt:507)
	at me.ash.reader.domain.service.GoogleReaderRssService$subscribe$1.invokeSuspend(GoogleReaderRssService.kt:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6c05df8, Dispatchers.Default]

**Comment by Dav-d** [comment]
It seems working now.
