### ISSUE TITLE
OPML importer fail

### ISSUE THREAD

**Issue by mzzntn** [Ashinch/ReadYou#922]
**1. Environment**

-   Device: Samsung A54
-   OS: Android 14
-   APP: 0.11.0

**2. Describe the bug**

Version: 0.11.0
Device: samsung SM-A546B
System: Android 14 (API 34)

Stack trace: 

be.ceau.opml.OpmlParseException: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:START_TAG <outline title='Eventi e Manifestazioni a Novara' category='Novara' type='rss' xmlUrl='https://www.marchiodoc.it/feed/'>@49:94 in java.io.InputStreamReader@60a110b) 
	at me.ash.reader.infrastructure.rss.OPMLDataSource.parseFileInputStream(OPMLDataSource.kt:300)
	at me.ash.reader.domain.service.OpmlService$saveToDatabase$2.invokeSuspend(OpmlService.kt:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@30548a6, Dispatchers.Default]
Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:START_TAG <outline title='Eventi e Manifestazioni a Novara' category='Novara' type='rss' xmlUrl='https://www.marchiodoc.it/feed/'>@49:94 in java.io.InputStreamReader@60a110b) 
	at com.android.org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at com.android.org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at com.android.org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1123)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at be.ceau.opml.OpmlParser.extract(OpmlParser.java:49)
	at me.ash.reader.infrastructure.rss.OPMLDataSource.parseFileInputStream(OPMLDataSource.kt:16)
	... 6 more

**Comment by SShwinA** [comment]
Have experienced the same in 0.11.1(Fdroid build), on MIUI 11.05(Android 9).  
I can select the file, but nothing happens. No crash or error message.  

Is there a workaround?
